### ISSUE TITLE
Welcome email - remove

### ISSUE THREAD

**Issue by gibbard** [dox/interviews#55]
Please remove Welcome Email function. In the 'Add New' screen I currently always untick the box that says E-Mail candidate confirmation letter. I believe this relates to the message in Email Settings called welcome_email. I do not use this function and am mindful of the possibility of correspondence to candidates being accidentally generated prematurely.

**Comment by dox** [comment]
I've changed the button, so by default it is now unchecked.  That way you can still use it, if you wish, but it won't matter if you forget about it.
