### ISSUE TITLE
Reports - short subject names

### ISSUE THREAD

**Issue by gibbard** [dox/interviews#56]
In the reports, e.g. the Skype report and the Arrivals report, are we able to abbreviate subject names or limit the number of characters thatappear in order to minimise text running across text.

**Comment by dox** [comment]
I can either limit the field to so many characters (say, 30?), or reduce the size of the text?

Failing that - I can just display the course code.  Let me know what you prefer...

**Comment by gibbard** [comment]
Please can we slightly reduce the size of the text in all fields AND reduce the amount of characters displayed in the subject field to a maximum of 35 - these 35 characters would ideally include as much of the subject name as possible plus the course code. Thank you!
